stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/pima_diabetes.csv
    outs:
      - data/processed/clean_data.csv

  train:
    cmd: python src/train_model.py
    deps:
      - data/processed/clean_data.csv
    outs:
      - models/diabetes_model.pkl
