name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python (use same version as local)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Upgrade pip + install dependencies cleanly
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # Step 4: Run your tests or scripts
      - name: Run tests
        run: |
          echo "✅ All dependencies installed successfully!"
          # Add your testing command here if needed
          # e.g. pytest tests/

      # Step 5: Verify Python environment (optional but useful)
      - name: Verify environment
        run: |
          python --version
          pip list
